default: &default
  adapter: mysql2
  timeout: 5000
  host: <%= ENV.fetch('MYSQL_HOST') %>
  username: <%= ENV.fetch('MYSQL_USER') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') %>
  encoding: utf8

development:
  <<: *default
  database: <%= ENV.fetch('MYSQL_DB') %>

test:
  <<: *default
  database: <%= ENV.fetch('MYSQL_TEST_DB') %>

production:
  <<: *default
  database: <%= ENV.fetch('MYSQL_PROD_DB') %>